/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poos2;

/**
 *
 * @author Dell
 */
public class VtnP extends javax.swing.JFrame {

    /**
     * Creates new form Rnp
     */
    public VtnP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnu = new javax.swing.JMenuBar();
        mnuP = new javax.swing.JMenu();
        mnuPP = new javax.swing.JMenu();
        mnuPPA = new javax.swing.JMenuItem();
        mnuPPB = new javax.swing.JMenuItem();
        mnuPPC = new javax.swing.JMenuItem();
        mnuPPM = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuNP = new javax.swing.JMenu();
        mnuPNPA = new javax.swing.JMenuItem();
        mnuPNPB = new javax.swing.JMenuItem();
        mnuPNPC = new javax.swing.JMenuItem();
        mnuPNPM = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuCG = new javax.swing.JMenuItem();
        mnuH = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mnuP.setText("Productos");

        mnuPP.setText("Perecederos");

        mnuPPA.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuPPA.setText("Altas");
        mnuPPA.setToolTipText("altas de productos perecederos");
        mnuPPA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuPPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPPAActionPerformed(evt);
            }
        });
        mnuPP.add(mnuPPA);

        mnuPPB.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuPPB.setText("Bajas");
        mnuPPB.setToolTipText("bajas de productos perecederos");
        mnuPPB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuPP.add(mnuPPB);

        mnuPPC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuPPC.setText("Consultas");
        mnuPPC.setToolTipText("Consultas de productos perecederos");
        mnuPPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuPP.add(mnuPPC);

        mnuPPM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuPPM.setText("Modificaciones");
        mnuPPM.setToolTipText("modificaciones de productos perecederos");
        mnuPPM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuPP.add(mnuPPM);

        mnuP.add(mnuPP);
        mnuP.add(jSeparator1);

        mnuNP.setText("NoPerecederos");

        mnuPNPA.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        mnuPNPA.setText("Altas");
        mnuPNPA.setToolTipText("altas de productos no perecederos");
        mnuPNPA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuNP.add(mnuPNPA);

        mnuPNPB.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        mnuPNPB.setText("Bajas");
        mnuPNPB.setToolTipText("bajas de productos no perecederos");
        mnuPNPB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuNP.add(mnuPNPB);

        mnuPNPC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        mnuPNPC.setText("Consultas");
        mnuPNPC.setToolTipText("Consultas de productos no perecederos");
        mnuPNPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuNP.add(mnuPNPC);

        mnuPNPM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        mnuPNPM.setText("Modificaciones");
        mnuPNPM.setToolTipText("modificaciones de no productos perecederos");
        mnuPNPM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuNP.add(mnuPNPM);

        mnuP.add(mnuNP);
        mnuP.add(jSeparator2);

        mnuCG.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuCG.setText("Consultas Generales");
        mnuCG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuP.add(mnuCG);

        mnu.add(mnuP);

        mnuH.setText("Herramientas");
        mnu.add(mnuH);

        setJMenuBar(mnu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuPPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPPAActionPerformed
        new VtnPPA() .setVisible(true);
    }//GEN-LAST:event_mnuPPAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuBar mnu;
    private javax.swing.JMenuItem mnuCG;
    private javax.swing.JMenu mnuH;
    private javax.swing.JMenu mnuNP;
    private javax.swing.JMenu mnuP;
    private javax.swing.JMenuItem mnuPNPA;
    private javax.swing.JMenuItem mnuPNPB;
    private javax.swing.JMenuItem mnuPNPC;
    private javax.swing.JMenuItem mnuPNPM;
    private javax.swing.JMenu mnuPP;
    private javax.swing.JMenuItem mnuPPA;
    private javax.swing.JMenuItem mnuPPB;
    private javax.swing.JMenuItem mnuPPC;
    private javax.swing.JMenuItem mnuPPM;
    // End of variables declaration//GEN-END:variables
}
